### ISSUE TITLE
InvalidValueError while trying to translate maec report to stix

### ISSUE THREAD

**Issue by fugitive101** [MAECProject/maec5-to-stix2-translator#5]
running: $ maec2stix report.MAEC-5.0.json
returns: stix2.exceptions.InvalidValueError: Invalid value for Bundle 'objects': Unexpected properties for MalwareAnalysis: (av_result).

The report is generated by cuckoo sandbox v2.07

What am I doing wrong?

**Full details:**

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/stix2/base.py", line 104, in _check_property
    kwargs[prop_name] = prop.clean(kwargs[prop_name])
  File "/home/user/.local/lib/python3.8/site-packages/stix2/properties.py", line 234, in clean
    result = [
  File "/home/user/.local/lib/python3.8/site-packages/stix2/properties.py", line 235, in <listcomp>
    self.contained.clean(item)
  File "/home/user/.local/lib/python3.8/site-packages/stix2/properties.py", line 721, in clean
    parsed_obj = parse(dictified, allow_custom=self.allow_custom)
  File "/home/user/.local/lib/python3.8/site-packages/stix2/parsing.py", line 47, in parse
    obj = dict_to_stix2(obj, allow_custom, version)
  File "/home/user/.local/lib/python3.8/site-packages/stix2/parsing.py", line 142, in dict_to_stix2
    return obj_class(allow_custom=allow_custom, **stix_dict)
  File "/home/user/.local/lib/python3.8/site-packages/stix2/base.py", line 168, in __init__
    raise ExtraPropertiesError(cls, extra_kwargs)
stix2.exceptions.ExtraPropertiesError: Unexpected properties for MalwareAnalysis: (av_result).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/maec2stix", line 11, in <module>
    load_entry_point('maec2stix==1.0', 'console_scripts', 'maec2stix')()
  File "/usr/local/lib/python3.8/dist-packages/maec2stix-1.0-py3.8.egg/maec2stix/cli.py", line 77, in main
  File "/usr/local/lib/python3.8/dist-packages/maec2stix-1.0-py3.8.egg/maec2stix/translator.py", line 1317, in translate_package_to_object
  File "/home/user/.local/lib/python3.8/site-packages/stix2/parsing.py", line 47, in parse
    obj = dict_to_stix2(obj, allow_custom, version)
  File "/home/user/.local/lib/python3.8/site-packages/stix2/parsing.py", line 142, in dict_to_stix2
    return obj_class(allow_custom=allow_custom, **stix_dict)
  File "/home/user/.local/lib/python3.8/site-packages/stix2/v21/bundle.py", line 34, in __init__
    super(Bundle, self).__init__(**kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/stix2/base.py", line 198, in __init__
    self._check_property(prop_name, prop_metadata, setting_kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/stix2/base.py", line 110, in _check_property
    six.raise_from(
  File "<string>", line 3, in raise_from
stix2.exceptions.InvalidValueError: Invalid value for Bundle 'objects': Unexpected properties for MalwareAnalysis: (av_result).

**Comment by clenk** [comment]
Hi @fugitive101, this error is caused because a property was renamed in STIX 2.1 since this script was written. I'll put in a fix.
